# this manifest for trying default image on your Kubernetes cluster.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkcm-rw
rules:
- apiGroups: [""]
  resourceNames: ["checkcm"]
  resources: ["configmaps"]
  verbs: ["get", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkcm-rw
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: checkcm-rw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkcm-rw
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: checkcm-rw
---
apiVersion: v1
kind: Pod
metadata:
  name: running-check
  namespace: loadtest
spec:
  serviceAccountName: checkcm-rw
  containers:
  - image: cyberagentoss/intelligent-hpa-fittingjob:latest
    name: fittingjob
    volumeMounts:
    - name: fittingjob-config
      mountPath: /fittingjob-config
  restartPolicy: Never
  volumes:
  - name: fittingjob-config
    configMap:
      name: checkcm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkcm
  namespace: loadtest
data:
  config.json: >-
    {
        "provider":{
            "datadog":{
                "apikey":"xxx",
                "appkey":"yyy"
            }
        },
        "targetMetricsName":"nginx.net.request_per_s",
        "targetTags":{
            "kube_namespace":"loadtest",
            "kube_deployment":"nginx"
        },
        "seasonality":"auto",
        "dataConfigMapName":"checkcm",
        "dataConfigMapNamespace":"loadtest"
    }
