---
apiVersion: ihpa.ake.cyberagent.co.jp/v1beta1
kind: IntelligentHorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  estimationGapMinutes: 5
  estimationMode: adjust
  metricProvider:
    name: datadog
    datadog:
      apikey: xxx
      appkey: yyy
  fittingJobConfig: 
    seasonality: daily
    executeOn: 12
    changePointDetectionConfig:
      percentageThreshold: 50
      windowSize: 100
      trajectoryRows: 50
      trajectoryFeatures: 5
      testRows: 50
      testFeatures: 5
      lag: 288
    image: your-job-image:v1
    imagePullSecrets:
    - name: pull-secret
    serviceAccountName: ihpa-configmap-rw
  template:
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: nginx
      minReplicas: 1
      maxReplicas: 5
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
      - type: External
        external:
          metric:
            name: nginx.net.request_per_s
            selector:
              matchLabels:
                kube_namespace: loadtest
                kube_deployment: nginx
                kube_container_name: nginx
                kube_system_uid: xxx
          target:
            type: AverageValue
            averageValue: "10"
