# permissions to do edit fittingjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fittingjob-editor-role
rules:
- apiGroups:
  - ihpa.ake.cyberagent.co.jp
  resources:
  - fittingjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ihpa.ake.cyberagent.co.jp
  resources:
  - fittingjobs/status
  verbs:
  - get
  - patch
  - update
